# /// script
# requires-python = ">=3.11"
# dependencies = [
#   "pydantic>=2.6",
# ]
# ///
"""Render a research report (JSON) as a Typst source file, ready for
`typst compile` to an A5 PDF suitable for reading on an e-reader.

Usage:
    uv run --script typst-export.py --in report.json --out report.typ
    uv run --script typst-export.py < report.json > report.typ
    uv run --script typst-export.py --in report.json --out report.typ --compile

The input JSON schema is the Report model below (see references/typst-format.md).
All report text is inserted as Typst string literals, so arbitrary content is
rendered verbatim with no markup surprises.
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path
from typing import Annotated, Literal, Optional, Union

from pydantic import BaseModel, Field, ValidationError, model_validator


# --- report model -----------------------------------------------------------

class Paragraph(BaseModel):
    type: Literal["paragraph"] = "paragraph"
    text: str


class Bullets(BaseModel):
    type: Literal["bullets"] = "bullets"
    items: list[str]


class Numbered(BaseModel):
    type: Literal["numbered"] = "numbered"
    items: list[str]


class Table(BaseModel):
    type: Literal["table"] = "table"
    headers: list[str]
    rows: list[list[str]]

    @model_validator(mode="after")
    def _rows_match_headers(self) -> "Table":
        width = len(self.headers)
        for i, row in enumerate(self.rows):
            if len(row) != width:
                raise ValueError(
                    f"table row {i} has {len(row)} cell(s) but there are {width} header(s)"
                )
        return self


class Quote(BaseModel):
    type: Literal["quote"] = "quote"
    text: str
    attribution: Optional[str] = None


class Code(BaseModel):
    type: Literal["code"] = "code"
    text: str
    lang: Optional[str] = None


class Image(BaseModel):
    type: Literal["image"] = "image"
    path: str
    caption: Optional[str] = None


Block = Annotated[
    Union[Paragraph, Bullets, Numbered, Table, Quote, Code, Image],
    Field(discriminator="type"),
]


class Section(BaseModel):
    heading: str
    level: int = 2
    blocks: list[Block] = Field(default_factory=list)


class Reference(BaseModel):
    key: str
    text: str
    url: Optional[str] = None


class Report(BaseModel):
    title: str
    subtitle: Optional[str] = None
    date: Optional[str] = None
    summary: str
    sections: list[Section] = Field(default_factory=list)
    open_questions: list[str] = Field(default_factory=list)
    references: list[Reference] = Field(default_factory=list)


# --- Typst rendering --------------------------------------------------------

PREAMBLE = '''// Generated by research-typst. A5 research report.
#set document(title: {title})
#set page(paper: "a5", margin: (x: 1.4cm, y: 1.6cm), numbering: "1")
#set text(size: 11pt, lang: "en")
#set par(justify: true, leading: 0.68em, spacing: 1.05em)
#set heading(numbering: none)
#show heading: set block(above: 1.2em, below: 0.6em)
#show link: set text(fill: rgb("#1a5fb4"))
'''


def tstr(value: object) -> str:
    """Render a value as a Typst string literal `"..."`. Inserted as `#"..."` in
    markup it yields literal text with no markup interpretation. Only backslash
    and double-quote need escaping inside a Typst string; newlines are folded."""
    s = "" if value is None else str(value)
    s = s.replace("\\", "\\\\").replace('"', '\\"')
    s = s.replace("\r\n", " ").replace("\n", " ").replace("\r", " ")
    return '"' + s + '"'


def render_block(block: Block) -> str:
    if isinstance(block, Paragraph):
        return f"#{tstr(block.text)}\n"
    if isinstance(block, Bullets):
        items = "".join(f"  {tstr(it)},\n" for it in block.items)
        return f"#list(\n{items})\n"
    if isinstance(block, Numbered):
        items = "".join(f"  {tstr(it)},\n" for it in block.items)
        return f"#enum(\n{items})\n"
    if isinstance(block, Table):
        cells = "".join(f"  table.cell(fill: luma(230))[#strong({tstr(h)})],\n" for h in block.headers)
        for row in block.rows:
            cells += "".join(f"  {tstr(c)},\n" for c in row)
        return f"#table(\n  columns: {len(block.headers)},\n  stroke: 0.5pt + luma(180),\n  inset: 6pt,\n{cells})\n"
    if isinstance(block, Quote):
        attr = f", attribution: {tstr(block.attribution)}" if block.attribution else ""
        return f"#quote(block: true{attr})[#{tstr(block.text)}]\n"
    if isinstance(block, Code):
        lang = f", lang: {tstr(block.lang)}" if block.lang else ""
        return f"#raw({tstr(block.text)}, block: true{lang})\n"
    if isinstance(block, Image):
        caption = f", caption: [#{tstr(block.caption)}]" if block.caption else ""
        return f"#figure(image({tstr(block.path)}, width: 100%){caption})\n"
    return ""


def render(report: Report) -> str:
    parts: list[str] = [PREAMBLE.replace("{title}", tstr(report.title))]

    title_lines = [f'  #text(size: 20pt, weight: "bold")[#{tstr(report.title)}]']
    if report.subtitle:
        title_lines.append(f'  #linebreak()\n  #v(0.2em)\n  #text(size: 13pt, style: "italic")[#{tstr(report.subtitle)}]')
    if report.date:
        title_lines.append(f'  #linebreak()\n  #v(0.2em)\n  #text(size: 10pt, fill: luma(110))[#{tstr(report.date)}]')
    parts.append("\n#align(center)[\n" + "\n".join(title_lines) + "\n]\n\n#v(0.5cm)\n")

    parts.append(
        '#block(fill: luma(240), inset: 10pt, radius: 4pt, width: 100%)[\n'
        '  #text(weight: "bold")[Summary]\n  #linebreak()\n  #'
        + tstr(report.summary)
        + "\n]\n\n#v(0.3cm)\n"
    )

    for section in report.sections:
        marker = "===" if section.level >= 3 else "=="
        parts.append(f"\n{marker} #{tstr(section.heading)}\n\n")
        for block in section.blocks:
            parts.append(render_block(block) + "\n")

    if report.open_questions:
        items = "".join(f"  {tstr(q)},\n" for q in report.open_questions)
        parts.append(f"\n== Open questions\n\n#list(\n{items})\n")

    if report.references:
        refs = ""
        for ref in report.references:
            link = f" #link({tstr(ref.url)})" if ref.url else ""
            refs += f"  [#strong({tstr(ref.key)}) #{tstr(ref.text)}{link}],\n"
        parts.append(f"\n== References\n\n#enum(\n{refs})\n")

    return "".join(parts)


def main() -> int:
    parser = argparse.ArgumentParser(description="Render a research report JSON as Typst.")
    parser.add_argument("--in", dest="infile", type=Path, default=None, help="report JSON (default: stdin)")
    parser.add_argument("--out", dest="outfile", type=Path, default=None, help="output .typ (default: stdout)")
    parser.add_argument("--compile", action="store_true", help="also run `typst compile` to a PDF next to --out")
    args = parser.parse_args()

    try:
        raw = args.infile.read_text(encoding="utf-8") if args.infile else sys.stdin.read()
    except FileNotFoundError:
        sys.stderr.write(f"error: input file not found: {args.infile}\n")
        return 1
    except OSError as error:
        sys.stderr.write(f"error: cannot read input file '{args.infile}': {error}\n")
        return 1

    try:
        report = Report.model_validate_json(raw)
    except ValidationError as error:
        sys.stderr.write(
            "error: invalid report JSON (see references/typst-format.md for the schema):\n"
            f"{error}\n"
        )
        return 1

    rendered = render(report)

    if args.outfile:
        args.outfile.write_text(rendered, encoding="utf-8")
    else:
        sys.stdout.write(rendered)

    if args.compile:
        if not args.outfile:
            sys.stderr.write("error: --compile requires --out\n")
            return 2
        pdf = args.outfile.with_suffix(".pdf")
        try:
            return subprocess.run(["typst", "compile", str(args.outfile), str(pdf)]).returncode
        except FileNotFoundError:
            sys.stderr.write(
                "error: 'typst' not found on PATH — install it to compile PDFs (https://typst.app)\n"
            )
            return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())
